name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.10.1
        with:
          clang-format-version: "14"
          check-path: "src"
          fallback-style: "Google"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.10.0
        with:
          split_workflow: true

      - uses: actions/upload-artifact@v3
        with:
          name: clang-tidy-review
          path: |
            clang-tidy-review-output.json
            clang-tidy-review-metadata.json

      - uses: ZedThree/clang-tidy-review/post@v0.10.1
