name: clang-tidy-review

on:
  push: {}
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clang-tidy review
        uses: ZedThree/clang-tidy-review@v0.10.1
        id: review
        with:
          apt_packages: "libgtest-dev"
          split_workflow: true

      - uses: actions/upload-artifact@v3
        with:
          name: clang-tidy-review
          path: |
            clang-tidy-review-output.json
            clang-tidy-review-metadata.json
